# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-04-13 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200411_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 4, 13, 7, 58, 49, 99553, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
