# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-04-18 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_remove_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
