# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-04-18 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0016_auto_20200418_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
