# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-05-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import rango.models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0035_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
